name: Python package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Smoke test – import module
        run: |
          python - <<'PY'
          import importlib, sys
          try:
              importlib.import_module("analysis_Rotation")
              print("✅ import OK")
          except Exception as e:
              print("❌ import failed:", e)
              sys.exit(1)
          PY

      - name: Smoke test – run script help
        run: python analysis_Rotation.py -h || true

      - name: Run pytest suite
        run: pytest -q
